sudo: false
language: node_js
node_js:
- 9

install:
- npm install

aliases:
  script: &script
    npm run test
    npm run lint
    npm run stylelint
    npm run build
  deploy: &deploy
    provider: heroku
    api_key:
      secure: kxTRKl/KpxYQv4B/i7Alsh0Gbk614Q2CxsV80N0SkPbGQHjOxATovw/T0v47HPqu7LxJrj/kQ/3sm1rAL3gIYkcVrkLI693ZB4Gt0PMq7zqHvIpCqkEExi6lMPNzIJfaDgDsPDQns/w8ufIpkQ2Gs0gcuoA+7FixzthhBZmVZa85+I88LL5Oclpr2qiqKlQJ9Fk6hAsjHz0MoYkJ+jNRma85EYuB7VQb8NJ/2ii//bsfIdWDxnlWlZIMlMiDPK+I2wun3PbhdVefL6sizo5Z+fcQ0A0jfNe3DyiUE0N32dnm4RlmfkZ5rBH7mBtYjdJyPLmY/67o0lbMNMdB5RC/P/poHpjK8rv0Hyy68NMQGehBFQeKKpgeappASY2r37jpFkICnNmDoKmpF2JVQny/dE9Z6IPdSK1oGoqZwHFNgoz5/Z/C+NJWbeaqwtRgNY53Lo+LE10jdoSIS+7iMcqgYhfJEXdAu3Fo5ue71krNiHFEqefKpis1S754Vz6U4Ab84fbRDqpZ0tZ+w0kuz+KftHNmVh9pRg1ze7ItQSLv/vJS2g9idedtOB/oSpK20utltH24+/g8RsIx62QVo4h+ndx2m8i0E5X17h3A7PR0yP/IWxaLB4C8fJcEFbd7OauJ9QfBuRlfr9zElPvbYOwzQU7q1RSTExhTUHeCnUBrnGs=
    skip_cleanup: true
    app: yandex-shri-task-456
    on:
      repo: akimy/task-345-NodeJS-CI-CD

jobs:
  include:
    - stage: Deploy (development)
      if: tag IS blank
    - script:
        <<: *script
      deploy:
        <<: *deploy
        on:
          tags: false

    - stage: Deploy (production)
      if: tag IS present
    - script:
        <<: *script
      deploy:
        <<: *deploy
        on:
          tags: true