language: node_js
node_js:
 - "9"
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run stylelint
  - npm run build
deploy:
  provider: heroku
  api_key: 0342da50-b8e9-41ae-b431-40cdfd0f2db2
  app: yandex-shri-task-3