sudo: false
language: node_js
node_js:
 - "9"
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run stylelint
  - npm run build

aliases:
  deploy: &deploy
    provider: heroku
    api_key: 
      secure: V0R48VDubcOskulW6ljVD8AeAY88UTAlR5Q05E6RsPlr/Rlte4Cyd0//9NqyvuY5vSxaq+1NDT3HxJH1gJ5Cg0rFcSN3IVZQyo9cl/pLJmNEsfDgif5LObJppGPAp3PUJNuhFOj8qSY7Hx++tcGKds+hI4NHLyX/0jFpyN83fsTGU0uQ5xizTpqbgyxqbEr1rlro0Z9gKtSsM68W1XIkAy2eNzrP4hjpR50cuj7U3tjBSOR//I2anKn0yHvXVX1GrAdpH5x2izfoH/vHkUYKbWVPcx22AfH5TpDBenNcim8P25wOVTHpoUMQdeEVJ64b5ZsUrad0ZEiz9NXxI/XDLJCy5vm2r5v8ekNSYh0Q7Opy7q4rGi1QfQfWcFpZv3fXeJfZr0NBDX9NtZeRoNjExRsCDRcueQLorFzA4dtA34iumavOKjCDX3K/TWlwCTH81Ekp7XlKTMlZsCn5vGxfZWa98MFtXCUYquoSx2vZ+xICD5aKDE3RMScAXr8mjN8Mh3qag+XjqMwU2b4rluYGeYNNWo4G/nnrP6XlcX9tF1cUwkkOb+5yby+rk6nOdEKXbXmIJq2J67fUWHcdnP0Y16loGIXEH/r9CMGgAfmeqZtjBuD5Eq4XK3dL447KwHsHc7PiuqLlPH+ZG+JDbHmGuBqwNR106xn6oNrUFWzrSRk=
    skip_cleanup: true

jobs:
  include:
    - stage: Deploy (development)
      if: tag IS blank
      script:
        - npm run build
      deploy:
        <<: *deploy
        app: yandex-shri-task-456

    - stage: Deploy (production)
      if: tag IS present
      script:
        - npm run build
      deploy:
        <<: *deploy
        app: yandex-shri-task-456
        on:
          tags: true