sudo: false
language: node_js
node_js:
 - "9"
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run stylelint
  - npm run build

aliases:
  deploy: &deploy
    provider: heroku
    api_key: 
      secure: KTr+i+jqQkcKb7Et6viBTIvlfcWwG5vD0a1HG532KnyofqOr/UK4PnyoFsE02fym0PJk+1qu5kok+30H3AbGD9gzcZK4dQcRqqqyWl/ri8yVBSJ5FzFK9s/9Hqk5Peh2e2/DZIduqWUhZslVe3u1GQM1R350ktaHlXQ+oJwJu+9elNgBssEFp0zm6f9fwhrILTVp5DUoZ5f2mu1zjSDEfOp8gvoT5aNbkc5dGmw1N+Ih6Upo2p3o0r8SSAYU/+6qhjBflW4b0N1jhvhlifBZYKIX1uOHdBSa+glnTl0kHdwMBPGkH1adB6EuFMbq6oYzXAceeHOyjaWUsUCE2GqAder2N/UE5cdqLaARObtrJ8XnA+Bup97t/ZhsT12c27NfFT8FWDY/uK4pKsuqvEps05b232PCDhEZU4NrfSH9PIJw+ZbG3Grb/6RyLpjMw/8MokHl1wl0Hzc/ZyXDOFOFp608c885dgTcuKMXQwz1LFQK+dV/TpWnrcC2Xk+1yu44W9ssvzVOginPsBn/SixTHBO/resqdysSkoT28HOTQKedQqyaaTs7RHJXyO+gFQ44Z6Jfl50P/zu1+YXzVfUliCL4RO5soXvdgugog9W1xbSSM3/h5pdJ54lfQ6kUuHoboVb0BR25A9XzXMdlzJIIbe0gGxPCYAU0iJuhdBFi++U=
    skip_cleanup: true

jobs:
  include:
    - stage: Deploy (development)
      if: tag IS blank
      script:
        - npm run build
      deploy:
        <<: *deploy
        app: yandex-shri-task-456

    - stage: Deploy (production)
      if: tag IS present
      script:
        - npm run build
      deploy:
        <<: *deploy
        app: yandex-shri-task-456
        on:
          tags: true