sudo: false
language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run stylelint
- npm run build
aliases:
  deploy:
    provider: heroku
    api_key:
      secure: bq88GdumwMqiMbKRSS4c0JfS/VoROHxyNxSTVaE30+wyThJDDsidGxt5K+6pMsMtV3W+kprJxBWu9UIHUNctsj0YLuM7NIdbrWQh3vWwg7r3HNIflK8lFM0taquGk4ohVHeS7bDSe3EVQVGQep2XjrGkEybNe/utrrHVopIKsAsyk/3forE8O0iuaM3d8setpaxq9Zt8TLi+UzJcom0gptw6eInyCWrZRgymzHxFSoOBIt0boNNmwT8sKHKUKrd62p1d6bx70XCT3LFUme+RzYF513UTacbxBB6YgKSuPe6YOFqLzE7OsDbGQbSX34ItSZ3hfSyYE8heEyoko2tp5/u+lEy7JfGELNSclf39SwGFh4QdINRL/JosnS64AyUzhzw9RnPZfX8UVZBWn7QU3Fnob49hCg3XogxQ6z4glLr1qEsIXyc20TdsxVbYQQShW5YZKuT9zF7vYyhj1MFgYrPrAPbP+40BpRVP04VJWf+euNAHNgT3pDzrU4bCWhCpccbt5CWO6gpcVmTuXbwLSA8EOBOYu9kdd34YB/CORJXPHf1VJqGShSZstFowX8KqrSax1XyOfL9bprEcuoqNzzugKLAE9x95geDCaJJfsDVt+czgXzoaIZ04SvCiixjUF5WgztGmENuijGwg8qIt7n9SQ8/Wnhc+v1QeBgFZeGI=
    on:
      repo: akimy/task-345-NodeJS-CI-CD
jobs:
  include:
  - stage: Deploy (development)
    if: tag IS blank
    script:
    - npm run build
    deploy:
      provider: heroku
      api_key: *1
      skip_cleanup: true
      app: yandex-shri-task-456
  - stage: Deploy (production)
    if: tag IS present
    script:
    - npm run build
    deploy:
      provider: heroku
      api_key: *1
      skip_cleanup: true
      app: yandex-shri-task-456
      on:
        tags: true